export type VerificationTier =
  | "A"
  | "B"
  | "C"
  | "D"
  | "E"
  | "F"
  | "G";

export type Automatable = "yes" | "partial" | "manual" | "n/a";

export type VerificationCheck = {
  code: string;
  tier: VerificationTier;
  label: string;
  description: string;
  blocking: boolean;
  automatable: Automatable;
  source: string;
  validFor: string;
  publicLabel: string | null;
};

export type TradeCategory = {
  slug: string;
  name: string;
  requiredChecks: string[];
  blockingChecks: string[];
  plMinimum: string;
  scopeRestriction: string | null;
};

export type VerificationState = {
  code: string;
  meaning: string;
  badge: string;
  listed: "Yes" | "No" | "Partially";
};

export type RiskWeight = {
  signal: string;
  weight: number;
};

// ---------------------------------------------------------------------------
// Verification states (Section 3)
// ---------------------------------------------------------------------------

export const VERIFICATION_STATES: VerificationState[] = [
  {
    code: "unverified",
    meaning: "Registered, checks not complete",
    badge: "None",
    listed: "No",
  },
  {
    code: "pending",
    meaning: "Checks submitted, in progress",
    badge: "None",
    listed: "No",
  },
  {
    code: "review",
    meaning: "Flagged, awaiting a human decision",
    badge: "None",
    listed: "No",
  },
  {
    code: "verified",
    meaning: "All Tier A, B and C checks passed",
    badge: "Standard badge",
    listed: "Yes",
  },
  {
    code: "certified",
    meaning: "Verified, plus all Tier D checks for their categories",
    badge: "Badge with trade credentials shown",
    listed: "Yes",
  },
  {
    code: "expired",
    meaning: "A time-limited check has lapsed",
    badge: "Revoked",
    listed: "No",
  },
  {
    code: "suspended",
    meaning: "Under investigation",
    badge: "Revoked",
    listed: "No",
  },
  {
    code: "restricted",
    meaning: "Listed, but one or more categories removed",
    badge: "Badge, reduced categories",
    listed: "Partially",
  },
  {
    code: "rejected",
    meaning: "Failed a blocking check",
    badge: "None",
    listed: "No",
  },
  {
    code: "banned",
    meaning: "Removed permanently. Identity flagged",
    badge: "None",
    listed: "No",
  },
];

// ---------------------------------------------------------------------------
// Check catalogue (Section 4)
// ---------------------------------------------------------------------------

export const CHECKS: VerificationCheck[] = [
  // Tier A. Identity (blocking)
  {
    code: "A1",
    tier: "A",
    label: "Government photo ID",
    description: "Passport or UK photocard driving licence",
    blocking: true,
    automatable: "yes",
    source: "IDV provider",
    validFor: "3 years",
    publicLabel: "Identity checked",
  },
  {
    code: "A2",
    tier: "A",
    label: "Liveness and face match",
    description: "Selfie video against A1",
    blocking: true,
    automatable: "yes",
    source: "IDV provider",
    validFor: "3 years",
    publicLabel: "Identity checked",
  },
  {
    code: "A3",
    tier: "A",
    label: "Proof of address",
    description: "Utility bill, bank statement or council tax, dated within 3 months",
    blocking: true,
    automatable: "partial",
    source: "Utility bill, bank statement or council tax, dated within 3 months",
    validFor: "12 months",
    publicLabel: "Address confirmed",
  },
  {
    code: "A4",
    tier: "A",
    label: "Age",
    description: "Derived from A1",
    blocking: true,
    automatable: "yes",
    source: "Derived from A1",
    validFor: "Permanent",
    publicLabel: null,
  },
  {
    code: "A5",
    tier: "A",
    label: "Right to work in the UK",
    description: "Home Office share code, or document check",
    blocking: true,
    automatable: "yes",
    source: "DIATF certified IDV provider",
    validFor: "Per expiry",
    publicLabel: "Right to work in the UK confirmed",
  },
  {
    code: "A6",
    tier: "A",
    label: "Sanctions and PEP screening",
    description: "OFSI consolidated list, UN, EU",
    blocking: true,
    automatable: "yes",
    source: "Screening provider",
    validFor: "Continuous monitoring",
    publicLabel: "Screened against UK and international sanctions lists",
  },
  {
    code: "A7",
    tier: "A",
    label: "Mobile number",
    description: "SMS one-time code",
    blocking: true,
    automatable: "yes",
    source: "SMS one-time code",
    validFor: "On change",
    publicLabel: null,
  },
  {
    code: "A8",
    tier: "A",
    label: "Email",
    description: "Verification link",
    blocking: true,
    automatable: "yes",
    source: "Verification link",
    validFor: "On change",
    publicLabel: null,
  },

  // Tier B. Business, common to all structures (blocking)
  {
    code: "B1",
    tier: "B",
    label: "Legal structure declared",
    description: "Self-declared, then evidenced",
    blocking: true,
    automatable: "n/a",
    source: "Self-declared, then evidenced",
    validFor: "Permanent",
    publicLabel: null,
  },
  {
    code: "B2",
    tier: "B",
    label: "Trading name",
    description: "Not misleadingly similar to an existing company, scheme or accreditation body",
    blocking: true,
    automatable: "manual",
    source: "Self-declared",
    validFor: "Permanent",
    publicLabel: null,
  },
  {
    code: "B3",
    tier: "B",
    label: "Business bank account",
    description: "Account name matches business or applicant name",
    blocking: true,
    automatable: "partial",
    source: "Open banking, or statement upload",
    validFor: "Permanent",
    publicLabel: "Business bank account confirmed in the trading name",
  },
  {
    code: "B4",
    tier: "B",
    label: "VAT registration, if claimed",
    description: "Number valid, name matches",
    blocking: true,
    automatable: "yes",
    source: "HMRC VAT number checking service",
    validFor: "Permanent",
    publicLabel: "Registered for VAT, number [X]",
  },
  {
    code: "B5",
    tier: "B",
    label: "Website ownership, if a site is claimed",
    description: "Control proven",
    blocking: true,
    automatable: "yes",
    source: "DNS TXT record or file upload",
    validFor: "Permanent",
    publicLabel: "Website ownership confirmed",
  },
  {
    code: "B6",
    tier: "B",
    label: "Trading address",
    description: "Cross-check against A3",
    blocking: true,
    automatable: "manual",
    source: "Cross-check against A3",
    validFor: "Permanent",
    publicLabel: null,
  },
  {
    code: "B7",
    tier: "B",
    label: "Duplicate and prior-removal check",
    description:
      "No match against previously suspended, rejected or banned identities, companies, addresses, phone numbers or bank accounts",
    blocking: true,
    automatable: "yes",
    source: "Internal",
    validFor: "Continuous monitoring",
    publicLabel: null,
  },

  // Tier C. Business, by legal structure
  // C1. Limited company and LLP (blocking)
  {
    code: "C1.1",
    tier: "C",
    label: "Company exists",
    description: "Company number resolves",
    blocking: true,
    automatable: "yes",
    source: "Companies House API",
    validFor: "Permanent",
    publicLabel: "Companies House verified",
  },
  {
    code: "C1.2",
    tier: "C",
    label: "Company status",
    description:
      "Active. Reject dissolved, liquidation, administration, receivership, voluntary-arrangement",
    blocking: true,
    automatable: "yes",
    source: "Companies House API",
    validFor: "Permanent",
    publicLabel: "Companies House verified",
  },
  {
    code: "C1.3",
    tier: "C",
    label: "Applicant is an officer or PSC",
    description: "Applicant name matches a current director or person with significant control",
    blocking: true,
    automatable: "yes",
    source: "Companies House officers and PSC endpoints",
    validFor: "Permanent",
    publicLabel: "Confirmed as a director of the business",
  },
  {
    code: "C1.4",
    tier: "C",
    label: "Registered office",
    description: "Present and in the UK",
    blocking: true,
    automatable: "yes",
    source: "Companies House API",
    validFor: "Permanent",
    publicLabel: null,
  },
  {
    code: "C1.5",
    tier: "C",
    label: "SIC codes",
    description: "At least one plausible for the trade claimed. Mismatch flags for review, does not auto-reject",
    blocking: true,
    automatable: "yes",
    source: "Companies House API",
    validFor: "Permanent",
    publicLabel: null,
  },
  {
    code: "C1.6",
    tier: "C",
    label: "Incorporation date",
    description: "Recorded. Under 6 months routes to review",
    blocking: true,
    automatable: "yes",
    source: "Companies House API",
    validFor: "Permanent",
    publicLabel: null,
  },
  {
    code: "C1.7",
    tier: "C",
    label: "Filing status",
    description: "Accounts and confirmation statement not overdue. Overdue routes to review",
    blocking: true,
    automatable: "yes",
    source: "Companies House API",
    validFor: "Permanent",
    publicLabel: null,
  },
  {
    code: "C1.8",
    tier: "C",
    label: "Disqualified directors",
    description: "No match against the applicant or any current officer",
    blocking: true,
    automatable: "yes",
    source: "Companies House disqualified officers register",
    validFor: "Permanent",
    publicLabel: "Checked against the disqualified directors register",
  },
  {
    code: "C1.9",
    tier: "C",
    label: "Insolvency history of officers",
    description: "No current bankruptcy, DRO or IVA against the applicant",
    blocking: true,
    automatable: "yes",
    source: "Individual Insolvency Register, Insolvency Service",
    validFor: "Permanent",
    publicLabel: "Checked against the Individual Insolvency Register",
  },
  {
    code: "C1.10",
    tier: "C",
    label: "Charges and mortgages",
    description: "Recorded. Informational, feeds risk score only",
    blocking: false,
    automatable: "yes",
    source: "Companies House API",
    validFor: "Permanent",
    publicLabel: null,
  },

  // C2. Sole trader and partnership (blocking)
  {
    code: "C2.1",
    tier: "C",
    label: "UTR held",
    description: "SA302, tax year overview, UTR letter, or self-assessment confirmation",
    blocking: true,
    automatable: "manual",
    source: "SA302, tax year overview, UTR letter, or self-assessment confirmation",
    validFor: "Permanent",
    publicLabel: "Registered as a sole trader, tax reference confirmed",
  },
  {
    code: "C2.2",
    tier: "C",
    label: "Trading history",
    description: "Bank statements, invoices, or filed self-assessment covering at least 6 months",
    blocking: true,
    automatable: "manual",
    source: "Bank statements, invoices, or filed self-assessment covering at least 6 months",
    validFor: "Permanent",
    publicLabel: "Trading history confirmed",
  },
  {
    code: "C2.3",
    tier: "C",
    label: "Personal insolvency",
    description: "No current bankruptcy, debt relief order or individual voluntary arrangement",
    blocking: true,
    automatable: "yes",
    source: "Individual Insolvency Register, Insolvency Service",
    validFor: "Permanent",
    publicLabel: "Checked against the Individual Insolvency Register",
  },
  {
    code: "C2.4",
    tier: "C",
    label: "County court judgments",
    description:
      "Unsatisfied CCJs recorded and scored. Multiple or recent unsatisfied judgments route to review",
    blocking: true,
    automatable: "yes",
    source: "Registry Trust, TrustOnline",
    validFor: "Permanent",
    publicLabel: null,
  },
  {
    code: "C2.5",
    tier: "C",
    label: "Director disqualification",
    description:
      "No match. A disqualified director trading as a sole trader is lawful but is a material risk signal",
    blocking: true,
    automatable: "yes",
    source: "Companies House disqualified officers register",
    validFor: "Permanent",
    publicLabel: "Checked against the disqualified directors register",
  },
  {
    code: "C2.6",
    tier: "C",
    label: "Prior company history",
    description:
      "Dissolved or liquidated companies in the same trade within 3 years route to review. This is the phoenixing signal for sole traders",
    blocking: true,
    automatable: "yes",
    source: "Companies House officer search by name and date of birth",
    validFor: "Permanent",
    publicLabel: null,
  },
  {
    code: "C2.7",
    tier: "C",
    label: "Business bank account in the trading name",
    description: "Name match",
    blocking: true,
    automatable: "partial",
    source: "As B3",
    validFor: "Permanent",
    publicLabel: "Business bank account confirmed in the trading name",
  },
  {
    code: "C2.8",
    tier: "C",
    label: "Public presence",
    description: "Google Business Profile, website, social, trade directories",
    blocking: true,
    automatable: "partial",
    source: "Google Business Profile, website, social, trade directories",
    validFor: "Permanent",
    publicLabel: null,
  },

  // Tier D. Insurance (blocking)
  {
    code: "D1",
    tier: "D",
    label: "Public liability",
    description:
      "£1m absolute minimum. £2m standard for most trades. £5m required for roofing, scaffolding, asbestos, demolition, structural and any work at height",
    blocking: true,
    automatable: "manual",
    source: "Public liability insurance certificate",
    validFor: "To policy expiry",
    publicLabel: "Public liability cover of £[X]m, confirmed and monitored",
  },
  {
    code: "D2",
    tier: "D",
    label: "Employer's liability",
    description:
      "£5m minimum. Legally mandatory where anyone is employed, including casual and temporary staff",
    blocking: true,
    automatable: "manual",
    source: "Employer's liability insurance certificate",
    validFor: "To policy expiry",
    publicLabel: "Employer's liability insurance of £[X]m confirmed",
  },
  {
    code: "D3",
    tier: "D",
    label: "Professional indemnity",
    description:
      "Required where design, specification, survey or advice is offered. £250k minimum",
    blocking: true,
    automatable: "manual",
    source: "Professional indemnity insurance certificate",
    validFor: "To policy expiry",
    publicLabel: "Professional indemnity insurance confirmed",
  },
  {
    code: "D4",
    tier: "D",
    label: "Insurer authorisation",
    description: "Insurer authorised to write the class of business",
    blocking: true,
    automatable: "yes",
    source: "FCA Financial Services Register",
    validFor: "Per check",
    publicLabel: "Insurer confirmed as FCA authorised",
  },
  {
    code: "D5",
    tier: "D",
    label: "Employment declaration",
    description: "Self-declared at signup, revisited annually",
    blocking: true,
    automatable: "manual",
    source: "Self-declared at signup, revisited annually",
    validFor: "12 months",
    publicLabel: "No employees, employer's liability not required",
  },

  // Tier E. Trade certification
  // E1. Legally mandatory (blocking)
  {
    code: "E1.1",
    tier: "E",
    label: "Gas Safe Register",
    description: "Any gas work",
    blocking: true,
    automatable: "manual",
    source: "Gas Safe Register",
    validFor: "Per check",
    publicLabel: "Gas Safe registered, number [X]",
  },
  {
    code: "E1.2",
    tier: "E",
    label: "F-Gas certification",
    description: "Refrigerant handling, air conditioning, refrigeration, heat pumps",
    blocking: true,
    automatable: "manual",
    source: "F-Gas certification body searches, REFCOM and others",
    validFor: "Per check",
    publicLabel: "F-Gas certified, company and engineer",
  },
  {
    code: "E1.3",
    tier: "E",
    label: "HSE asbestos licence",
    description: "Licensable asbestos work",
    blocking: true,
    automatable: "manual",
    source: "HSE publishes a licence holder list",
    validFor: "Per check",
    publicLabel: "HSE asbestos licence held, number [X]",
  },
  {
    code: "E1.4",
    tier: "E",
    label: "Waste carriage",
    description: "Waste carriage in the course of business",
    blocking: true,
    automatable: "yes",
    source: "Environment Agency waste carrier, broker and dealer registration",
    validFor: "Per check",
    publicLabel: "Registered waste carrier, Environment Agency number [X]",
  },
  {
    code: "E1.5",
    tier: "E",
    label: "CISRS card",
    description: "Scaffolding erection",
    blocking: true,
    automatable: "manual",
    source: "CISRS card",
    validFor: "Per check",
    publicLabel: "CISRS carded scaffolder",
  },
  {
    code: "E1.6",
    tier: "E",
    label: "WaterSafe approved contractor",
    description: "Work on public water supply",
    blocking: true,
    automatable: "manual",
    source: "WaterSafe or a water company scheme",
    validFor: "Per check",
    publicLabel: "WaterSafe approved contractor",
  },

  // E2. Competent person schemes
  {
    code: "E2.1",
    tier: "E",
    label: "Part P electrical",
    description: "Electrical installation in dwellings, Part P",
    blocking: true,
    automatable: "manual",
    source:
      "NICEIC and ELECSA (both Certsure LLP), NAPIT, STROMA, APHC, BESCA, Blue Flame, Benchmark",
    validFor: "Per check",
    publicLabel: "Part P registered electrician, [scheme name], number [X]",
  },
  {
    code: "E2.2",
    tier: "E",
    label: "Windows and doors",
    description: "Replacement windows, doors, roof windows and rooflights",
    blocking: true,
    automatable: "manual",
    source: "FENSA, CERTASS, ASSURE (Network VEKA), Certsure, NAPIT, STROMA, BM TRADA, BSI, Blue Flame",
    validFor: "Per check",
    publicLabel: "[FENSA or CERTASS] registered, number [X]",
  },
  {
    code: "E2.3",
    tier: "E",
    label: "Oil-fired",
    description: "Oil-fired appliances and oil storage",
    blocking: true,
    automatable: "manual",
    source: "OFTEC, APHC, BESCA, Blue Flame, Certsure, NAPIT, STROMA",
    validFor: "Per check",
    publicLabel: "OFTEC registered, number [X]",
  },
  {
    code: "E2.4",
    tier: "E",
    label: "Solid fuel",
    description: "Solid fuel, stoves, biomass, chimneys",
    blocking: true,
    automatable: "manual",
    source: "HETAS, APHC, BESCA, Blue Flame, Certsure, NAPIT, OFTEC, STROMA",
    validFor: "Per check",
    publicLabel: "HETAS registered, number [X]",
  },
  {
    code: "E2.5",
    tier: "E",
    label: "Roof coverings",
    description: "Roof coverings, pitched and flat",
    blocking: true,
    automatable: "manual",
    source: "CompetentRoofer (NFRC), NAPIT",
    validFor: "Per check",
    publicLabel: "CompetentRoofer registered, number [X]",
  },
  {
    code: "E2.6",
    tier: "E",
    label: "Heating and hot water",
    description: "Heating and hot water systems",
    blocking: true,
    automatable: "manual",
    source: "APHC, BESCA, Blue Flame, Gas Safe, Certsure, HETAS, NAPIT, OFTEC, STROMA",
    validFor: "Per check",
    publicLabel: null,
  },
  {
    code: "E2.7",
    tier: "E",
    label: "Unvented hot water, G3",
    description: "Unvented hot water systems, G3",
    blocking: true,
    automatable: "manual",
    source: "G3 qualification, or a scheme covering it",
    validFor: "Per check",
    publicLabel: "G3 qualified for unvented hot water",
  },
  {
    code: "E2.8",
    tier: "E",
    label: "Cavity wall insulation",
    description: "Cavity wall insulation",
    blocking: true,
    automatable: "manual",
    source: "CIGA, BBA",
    validFor: "Per check",
    publicLabel: null,
  },
  {
    code: "E2.9",
    tier: "E",
    label: "Ventilation and air conditioning",
    description: "Ventilation and air conditioning systems",
    blocking: true,
    automatable: "manual",
    source: "BESCA, NAPIT, STROMA",
    validFor: "Per check",
    publicLabel: null,
  },

  // E3. Grant and tariff schemes
  {
    code: "E3.1",
    tier: "E",
    label: "MCS certification",
    description:
      "Solar PV, heat pumps, biomass, solar thermal, where the work is grant-funded, eligible for the Boiler Upgrade Scheme, or connected to an export tariff",
    blocking: true,
    automatable: "manual",
    source: "MCS certification",
    validFor: "Per check",
    publicLabel: "MCS certified, number [X]",
  },
  {
    code: "E3.2",
    tier: "E",
    label: "TrustMark registration",
    description: "Required alongside MCS for most government-backed retrofit schemes",
    blocking: true,
    automatable: "manual",
    source: "TrustMark registration",
    validFor: "Per check",
    publicLabel: "TrustMark registered, number [X]",
  },
  {
    code: "E3.3",
    tier: "E",
    label: "PAS 2030 and PAS 2035",
    description: "Retrofit and energy efficiency work under government schemes",
    blocking: true,
    automatable: "manual",
    source: "PAS 2030 and PAS 2035",
    validFor: "Per check",
    publicLabel: null,
  },

  // Tier F. Presence, history and reputation (non-blocking)
  {
    code: "F1",
    tier: "F",
    label: "Google Business Profile exists",
    description: "Profile found for the business name and area",
    blocking: false,
    automatable: "yes",
    source: "Google Places API",
    validFor: "Continuous monitoring",
    publicLabel: "Google Business Profile confirmed",
  },
  {
    code: "F2",
    tier: "F",
    label: "Name, address and phone consistency",
    description: "NAP matches Companies House or A3. Mismatch routes to review",
    blocking: false,
    automatable: "yes",
    source: "Places API against the application",
    validFor: "Continuous monitoring",
    publicLabel: "Business name, address and phone verified as consistent",
  },
  {
    code: "F3",
    tier: "F",
    label: "Profile claimed by the owner",
    description: "Ownership proven",
    blocking: false,
    automatable: "yes",
    source: "Google Business Profile API, owner OAuth",
    validFor: "Continuous monitoring",
    publicLabel: "Business profile claimed by the owner",
  },
  {
    code: "F4",
    tier: "F",
    label: "Profile age against review volume",
    description: "A profile under 3 months old with a high review count is a fraud signal",
    blocking: false,
    automatable: "yes",
    source: "Places API",
    validFor: "Continuous monitoring",
    publicLabel: null,
  },
  {
    code: "F5",
    tier: "F",
    label: "Review authenticity",
    description: "Clustered dates, duplicated phrasing, single-review reviewer accounts",
    blocking: false,
    automatable: "manual",
    source: "Manual scan",
    validFor: "Continuous monitoring",
    publicLabel: null,
  },
  {
    code: "F6",
    tier: "F",
    label: "Adverse media and open source",
    description: "Prosecutions, Trading Standards action, local press",
    blocking: false,
    automatable: "manual",
    source: "Manual and automated search",
    validFor: "Continuous monitoring",
    publicLabel: "Public records checked",
  },
  {
    code: "F7",
    tier: "F",
    label: "Third-party platform reviews",
    description: "Existing presence on other directories and what it says",
    blocking: false,
    automatable: "manual",
    source: "Manual",
    validFor: "Continuous monitoring",
    publicLabel: null,
  },
  {
    code: "F8",
    tier: "F",
    label: "Companies House filing history pattern",
    description: "Repeated late filings, multiple dissolved companies",
    blocking: false,
    automatable: "yes",
    source: "Companies House API",
    validFor: "Continuous monitoring",
    publicLabel: null,
  },

  // Tier G. Optional, evidenced where held
  {
    code: "G1",
    tier: "G",
    label: "Basic DBS",
    description:
      "Lawful for anyone to obtain about themselves. Relevant for work in occupied homes. Not mandatory, never a listing condition, displayed only where the tradesperson supplies it",
    blocking: false,
    automatable: "manual",
    source: "Basic DBS certificate",
    validFor: "Per check",
    publicLabel: "Holds a basic DBS certificate, issued [date]",
  },
  {
    code: "G2",
    tier: "G",
    label: "Health and safety qualification",
    description: "SSSTS, SMSTS, IOSH, first aid",
    blocking: false,
    automatable: "manual",
    source: "SSSTS, SMSTS, IOSH, first aid certificate",
    validFor: "Per check",
    publicLabel: "Holds [qualification]",
  },
  {
    code: "G3",
    tier: "G",
    label: "Asbestos awareness training",
    description: "Category 1 non-licensed work",
    blocking: false,
    automatable: "manual",
    source: "Asbestos awareness training certificate",
    validFor: "Per check",
    publicLabel: "Holds [qualification]",
  },
  {
    code: "G4",
    tier: "G",
    label: "Trade association membership",
    description: "As E4",
    blocking: false,
    automatable: "manual",
    source: "Trade association membership evidence",
    validFor: "Per check",
    publicLabel: "Member of [association]",
  },
  {
    code: "G5",
    tier: "G",
    label: "Manufacturer accreditation",
    description: "As E4",
    blocking: false,
    automatable: "manual",
    source: "Manufacturer accreditation evidence",
    validFor: "Per check",
    publicLabel: "[Manufacturer] approved installer",
  },
  {
    code: "G6",
    tier: "G",
    label: "Apprenticeship or NVQ certificates",
    description: "Evidenced by certificate upload",
    blocking: false,
    automatable: "manual",
    source: "Certificate upload",
    validFor: "Per check",
    publicLabel: "Holds [qualification]",
  },
];

// ---------------------------------------------------------------------------
// Trade categories (Section 6)
// ---------------------------------------------------------------------------

export const TRADE_CATEGORIES: TradeCategory[] = [
  {
    slug: "gas-engineer",
    name: "Gas engineer, boiler, central heating",
    requiredChecks: ["E1.1"],
    blockingChecks: ["E1.1"],
    plMinimum: "£2m",
    scopeRestriction: null,
  },
  {
    slug: "plumber-no-gas",
    name: "Plumber, no gas work",
    requiredChecks: ["E2.7"],
    blockingChecks: [],
    plMinimum: "£2m",
    scopeRestriction: null,
  },
  {
    slug: "plumber-with-gas",
    name: "Plumber, with gas",
    requiredChecks: ["E1.1"],
    blockingChecks: ["E1.1"],
    plMinimum: "£2m",
    scopeRestriction: null,
  },
  {
    slug: "electrician",
    name: "Electrician",
    requiredChecks: ["E2.1"],
    blockingChecks: ["E2.1"],
    plMinimum: "£2m",
    scopeRestriction: null,
  },
  {
    slug: "air-conditioning-refrigeration",
    name: "Air conditioning and refrigeration",
    requiredChecks: ["E1.2"],
    blockingChecks: ["E1.2"],
    plMinimum: "£2m",
    scopeRestriction: null,
  },
  {
    slug: "heat-pump-installer",
    name: "Heat pump installer",
    requiredChecks: ["E1.2", "E3.1"],
    blockingChecks: ["E1.2"],
    plMinimum: "£2m",
    scopeRestriction: null,
  },
  {
    slug: "solar-pv-solar-thermal",
    name: "Solar PV and solar thermal",
    requiredChecks: ["E3.1", "E2.1"],
    blockingChecks: [],
    plMinimum: "£2m",
    scopeRestriction: null,
  },
  {
    slug: "ev-charger-installer",
    name: "EV charger installer",
    requiredChecks: ["E2.1"],
    blockingChecks: ["E2.1"],
    plMinimum: "£2m",
    scopeRestriction: null,
  },
  {
    slug: "roofer",
    name: "Roofer",
    requiredChecks: ["E1.4", "E2.5"],
    blockingChecks: ["E1.4"],
    plMinimum: "£5m",
    scopeRestriction: null,
  },
  {
    slug: "builder-extensions-structural",
    name: "Builder, extensions, structural",
    requiredChecks: ["E1.4"],
    blockingChecks: ["E1.4"],
    plMinimum: "£5m",
    scopeRestriction: null,
  },
  {
    slug: "groundworks-drainage",
    name: "Groundworks and drainage",
    requiredChecks: ["E1.4"],
    blockingChecks: ["E1.4"],
    plMinimum: "£5m",
    scopeRestriction: null,
  },
  {
    slug: "demolition",
    name: "Demolition",
    requiredChecks: ["E1.4", "E1.3"],
    blockingChecks: ["E1.4", "E1.3"],
    plMinimum: "£5m",
    scopeRestriction: null,
  },
  {
    slug: "window-door-glazing",
    name: "Window, door and glazing fitter",
    requiredChecks: ["E2.2"],
    blockingChecks: ["E2.2"],
    plMinimum: "£2m",
    scopeRestriction: null,
  },
  {
    slug: "oil-fired-heating",
    name: "Oil-fired heating",
    requiredChecks: ["E2.3"],
    blockingChecks: ["E2.3"],
    plMinimum: "£2m",
    scopeRestriction: null,
  },
  {
    slug: "stove-chimney-solid-fuel",
    name: "Stove, chimney and solid fuel installer",
    requiredChecks: ["E2.4"],
    blockingChecks: ["E2.4"],
    plMinimum: "£2m",
    scopeRestriction: null,
  },
  {
    slug: "chimney-sweep",
    name: "Chimney sweep",
    requiredChecks: [],
    blockingChecks: [],
    plMinimum: "£1m",
    scopeRestriction: null,
  },
  {
    slug: "asbestos-removal",
    name: "Asbestos removal",
    requiredChecks: ["E1.3"],
    blockingChecks: ["E1.3"],
    plMinimum: "£5m",
    scopeRestriction: null,
  },
  {
    slug: "scaffolder",
    name: "Scaffolder",
    requiredChecks: ["E1.5"],
    blockingChecks: ["E1.5"],
    plMinimum: "£5m",
    scopeRestriction: null,
  },
  {
    slug: "plasterer-renderer",
    name: "Plasterer, renderer",
    requiredChecks: [],
    blockingChecks: [],
    plMinimum: "£1m",
    scopeRestriction: null,
  },
  {
    slug: "painter-decorator",
    name: "Painter and decorator",
    requiredChecks: [],
    blockingChecks: [],
    plMinimum: "£1m",
    scopeRestriction: null,
  },
  {
    slug: "tiler",
    name: "Tiler",
    requiredChecks: [],
    blockingChecks: [],
    plMinimum: "£1m",
    scopeRestriction: null,
  },
  {
    slug: "carpenter-joiner",
    name: "Carpenter and joiner",
    requiredChecks: [],
    blockingChecks: [],
    plMinimum: "£1m",
    scopeRestriction: null,
  },
  {
    slug: "kitchen-fitter",
    name: "Kitchen fitter",
    requiredChecks: ["E2.1", "E1.1"],
    blockingChecks: [],
    plMinimum: "£2m",
    scopeRestriction: null,
  },
  {
    slug: "bathroom-fitter",
    name: "Bathroom fitter",
    requiredChecks: ["E2.7", "E2.1"],
    blockingChecks: [],
    plMinimum: "£2m",
    scopeRestriction: null,
  },
  {
    slug: "flooring-fitter",
    name: "Flooring fitter",
    requiredChecks: [],
    blockingChecks: [],
    plMinimum: "£1m",
    scopeRestriction: null,
  },
  {
    slug: "locksmith",
    name: "Locksmith",
    requiredChecks: [],
    blockingChecks: [],
    plMinimum: "£1m",
    scopeRestriction: null,
  },
  {
    slug: "security-alarm-installer",
    name: "Security and alarm installer",
    requiredChecks: [],
    blockingChecks: [],
    plMinimum: "£2m",
    scopeRestriction: null,
  },
  {
    slug: "landscaper-gardener",
    name: "Landscaper and gardener",
    requiredChecks: ["E1.4"],
    blockingChecks: [],
    plMinimum: "£2m",
    scopeRestriction: null,
  },
  {
    slug: "tree-surgeon-arborist",
    name: "Tree surgeon and arborist",
    requiredChecks: ["E1.4"],
    blockingChecks: ["E1.4"],
    plMinimum: "£5m",
    scopeRestriction: null,
  },
  {
    slug: "fencing-decking",
    name: "Fencing and decking",
    requiredChecks: ["E1.4"],
    blockingChecks: [],
    plMinimum: "£1m",
    scopeRestriction: null,
  },
  {
    slug: "driveway-paving",
    name: "Driveway and paving",
    requiredChecks: ["E1.4"],
    blockingChecks: ["E1.4"],
    plMinimum: "£2m",
    scopeRestriction: null,
  },
  {
    slug: "damp-proofing-timber",
    name: "Damp proofing and timber treatment",
    requiredChecks: [],
    blockingChecks: [],
    plMinimum: "£2m",
    scopeRestriction: null,
  },
  {
    slug: "pest-control",
    name: "Pest control",
    requiredChecks: [],
    blockingChecks: [],
    plMinimum: "£2m",
    scopeRestriction: null,
  },
  {
    slug: "drainage-septic-tank",
    name: "Drainage and septic tank",
    requiredChecks: ["E1.4"],
    blockingChecks: ["E1.4"],
    plMinimum: "£5m",
    scopeRestriction: null,
  },
  {
    slug: "insulation-cavity-wall",
    name: "Insulation and cavity wall",
    requiredChecks: ["E2.8", "E3.2"],
    blockingChecks: [],
    plMinimum: "£2m",
    scopeRestriction: null,
  },
  {
    slug: "cleaner-domestic",
    name: "Cleaner, domestic",
    requiredChecks: [],
    blockingChecks: [],
    plMinimum: "£1m",
    scopeRestriction: null,
  },
  {
    slug: "removals-clearance",
    name: "Removals and clearance",
    requiredChecks: ["E1.4"],
    blockingChecks: ["E1.4"],
    plMinimum: "£2m",
    scopeRestriction: null,
  },
  {
    slug: "handyman",
    name: "Handyman",
    requiredChecks: [],
    blockingChecks: [],
    plMinimum: "£1m",
    scopeRestriction:
      "Handyman listings cover minor repairs and maintenance only. They may not carry out gas work, notifiable electrical work, work on unvented hot water systems, refrigerant handling, asbestos work, or structural alterations. A handyman offering any of these must register in that specific category and hold the required certification.",
  },
  {
    slug: "architectural-design",
    name: "Architectural and design services",
    requiredChecks: ["D3"],
    blockingChecks: ["D3"],
    plMinimum: "£1m plus PI",
    scopeRestriction: null,
  },
];

// ---------------------------------------------------------------------------
// Decision logic / risk (Section 7)
// ---------------------------------------------------------------------------

export const RISK_WEIGHTS: RiskWeight[] = [
  { signal: "Previously suspended or banned identity match", weight: 100 },
  { signal: "Undischarged bankruptcy or current IVA", weight: 60 },
  { signal: "Director disqualification match", weight: 60 },
  { signal: "Adverse media, substantiated", weight: 50 },
  {
    signal: "Two or more dissolved companies in the same trade within 3 years",
    weight: 40,
  },
  {
    signal: "Google Business Profile under 3 months old with 20 or more reviews",
    weight: 30,
  },
  { signal: "Unsatisfied CCJ within 12 months", weight: 25 },
  { signal: "Applicant not listed as an officer or PSC", weight: 25 },
  { signal: "Companies House filings overdue", weight: 20 },
  { signal: "Name, address and phone mismatch against Google", weight: 20 },
  { signal: "Company incorporated under 6 months", weight: 15 },
  {
    signal: "Proof of address does not match registered office",
    weight: 15,
  },
  { signal: "Insurance expiring within 30 days", weight: 10 },
  { signal: "SIC codes inconsistent with the trade claimed", weight: 10 },
  { signal: "No Google Business Profile found", weight: 10 },
];

export const REVIEW_THRESHOLD = 30;
